### ISSUE TITLE
Silence XML plaintext backup conversion?

### ISSUE THREAD

**Issue by JoeGretch** [tmo1/sms-ie#121]
Thank you for creating such a useful app.

Would you be willing to write a script that will convert the Silence XML plaintext backup file into a JSON file to be imported?

Here is a sample from the Silence backup:

<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>

<smses count="12972">
 <sms protocol="0" address="+15557639101" date="1606237355859" type="1" subject="null" body="I can&apos;t fri but I can Thur I don&apos;t need assistance picking it up and can come by tonight and pay if that works" toa="null" sc_toa="null" service_center="null" read="1" status="-1" locked="0" />
 <sms protocol="0" address="+15557639101" date="1606237237747" type="2" subject="null" body="Hi Tracy. The boiler is all disconnected and ready to be lifted from it&apos;s pad. Can you come in Friday some time to load it up? I have to leave on Saturday and will be away for a week, and will also be tied up all day on Thanksgiving.&#10;&#10;Please let me know if that will work out for you.&#10;&#10;Thanks!" toa="null" sc_toa="null" service_center="null" read="1" status="-1" locked="0" />
 <sms protocol="0" address="+15557639101" date="1606077873112" type="1" subject="null" body="Yes all good thx I think I can hook every thing up now that I&apos;ve looked at it hope all is well. With y&apos;all also" toa="null" sc_toa="null" service_center="null" read="1" status="-1" locked="0" />
 
                                     . . . . . . .
 
  <sms protocol="0" address="5556637843" date="1689601387150" type="1" subject="null" body="We are on our way to get gas and head out" toa="null" sc_toa="null" service_center="null" read="1" status="-1" locked="0" />
</smses>

Thank you again.

**Comment by tmo1** [comment]
I'm not promising to do it, but I'll consider it. The format doesn't look too complicated. Are there MMS messages, or only SMS?

**Comment by tmo1** [comment]
A conversion script is now available [here](https://github.com/tmo1/sms-ie/blob/master/tools/silence-convert.py) (documented [here](https://github.com/tmo1/sms-ie/blob/master/tools/Tools.md#silence-convertpy)). It works on the sample XML you provided, but please test and report back here.

**Comment by tmo1** [comment]
I looked into this, and it turns out that the problem is that Silence is emitting invalid XML - this was first reported [seven years ago](https://git.silence.dev/Silence/Silence-Android/-/issues/317)! You can try the `entityfixer` code [posted by Calvin-L in that thread](https://git.silence.dev/Silence/Silence-Android/-/issues/317#note_2314).

**Comment by DavidHenryThoreau** [comment]
@tmo1 Can you implement `entityfixer` in the https://github.com/tmo1/sms-ie/blob/master/tools/silence-convert.py ?

**Comment by DavidHenryThoreau** [comment]
```
./silence-convert.py SilencePlaintextBackup.xml
Traceback (most recent call last):
  File "/tmp/l/./silence-convert.py", line 46, in <module>
    tree = ET.parse(input_file)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/xml/etree/ElementTree.py", line 1218, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.11/xml/etree/ElementTree.py", line 580, in parse
    self._root = parser._parse_whole(source)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
xml.etree.ElementTree.ParseError: reference to invalid character number: line 75, column 108
```

**Comment by DavidHenryThoreau** [comment]
Nice feature, SMS are imported with emoji :+1: 

Do you think MMS can be save and restore ?
SMS groups (2 or 3 people are not restored)

**Comment by tmo1** [comment]
> Nice feature, SMS are imported with emoji 👍

I'm glad it's working!

> Do you think MMS can be save and restore ?
SMS groups (2 or 3 people are not restored) -> they're not in SilencePlaintextBackup.xml

We can obviously only restore data that's present in the XML file. If there's anything there that isn't being converted / restored, please post some examples and I'll take a look.

**Comment by DavidHenryThoreau** [comment]
> We can obviously only restore data that's present in the XML file. If there's anything there that isn't being converted / restored, please post some examples and I'll take a look.

MMS are stored in `/data/data/org.smssecure.smssecure/app_parts/part1001758086744762515.mms`

These files are encrypted : 
```
file part1001235047216594581.mms
part1001235047216594581.mms: data
```

**Comment by DavidHenryThoreau** [comment]
> We can obviously only restore data that's present in the XML file. If there's anything there that isn't being converted / restored, please post some examples and I'll take a look.

MMS are stored in `/data/data/org.smssecure.smssecure/app_parts/part1001758286944762215.mms`

These files are encrypted : 
```
file part1001235047216594581.mms
part1001235047216594581.mms: data
```

**Comment by tmo1** [comment]
Where do those files come from? What's the encryption scheme, and where are the keys? If you provide sample files and keys, I can take a look (if you're willing expose potentially private data and metadata), but there's no way I can do anything without that.

**Comment by DavidHenryThoreau** [comment]
> Where do those files come from? What's the encryption scheme, and where are the keys? If you provide sample files and keys, I can take a look (if you're willing expose potentially private data and metadata), but there's no way I can do anything without that.

I'd like to decrypt a file first , in order to see what file it's and then post it.


Here's the MMS database structure :
https://git.silence.dev/Silence/Silence-Android/-/blob/master/src/org/smssecure/smssecure/database/MmsDatabase.java

The keys to decrpyt are located in :
org.smssecure.smssecure/shared_prefs/SecureSMS-Preferences.xml

**Comment by tmo1** [comment]
Thanks. I'm not planning to comb through the code to figure out the database structure and encryption scheme, but if you make progress on it, please post your results here.

**Comment by dngray** [comment]
I created a tool to do this in python to txt format https://github.com/dngray/silence-backup-parse/blob/main/silence_backup_parse.py there were some specifics regarding emojis.

as for MMS those are not exported in the XML file.

**Comment by DavidHenryThoreau** [comment]
@dngray Nice, emoji and SMS are well exported by using @tmo1 source code
What is missing : 
- SMS with more than 2 people (which is not present in the XML)
- MMS see my previous messages

**Comment by dngray** [comment]
> SMS with more than 2 people (which is not present in the XML)

That's probably because those are actually MMS messages and not SMS.

**Comment by DavidHenryThoreau** [comment]
Yes, I don't have found what kind of algo is used to encrypt MMS files : 
`/data/data/org.smssecure.smssecure/app_parts/part1001758286944762215.mms`
Do you have any ideas about these files ? How to decrypt them ?
Keys are locate in : 
`org.smssecure.smssecure/shared_prefs/SecureSMS-Preferences.xml`

**Comment by tmo1** [comment]
> That's probably because those are actually MMS messages and not SMS.

Correct. SMS messages cannot have more than one recipient - messages sent to more than one recipient are automatically sent as MMS messages, even when they're only simple text messages with no "media" involved.

**Comment by DavidHenryThoreau** [comment]
@Pommede  https://github.com/tmo1/sms-ie/blob/master/tools/Tools.md#silence-convertpy

**Comment by Pommede** [comment]
that what i did, (first command) or something wrong on my command?

**Comment by Pommede** [comment]
thank for your response but i did all that (it's my text.. :-()

**Comment by DavidHenryThoreau** [comment]
You've missed `<` and `>`

**Comment by Pommede** [comment]
yeah the first command worked
python silence-xml-fixer.py <SilencePlaintextBackup.xml> SilencePlaintextBackupfixed.xml
but the second
no <> if i put those i've got 
fish: Expected a string, but found end of the input

but python silence-convert.py SilencePlaintextBackupfixed.xml
i've got a zip with something....i'll try to another sms app
thks

**Comment by Pommede** [comment]
it's workin !! :-)
many thks.
no mms but it's a silence issue ?

**Comment by Pommede** [comment]
oki, very good job, i was afraid to be stuck with silence rrrr

**Comment by DavidHenryThoreau** [comment]
I'm looking at `org.smssecure.smssecure/shared_prefs/SecureSMS-Preferences.xml` it mentions `curve25519`

Rapid search can lead to : 
https://github.com/topics/curve25519
The rage project may can decrypt file ?? 

`-d, --decrypt               Decrypt the input.`
https://github.com/str4d/rage#passphrase-protected-identity-files
https://github.com/str4d/rage

**Comment by tmo1** [comment]
Silence / SMSSecure [uses](https://silence.im/faq/) the [Signal encryption protocol](https://signal.org/docs/specifications/x3dh/), which uses / can use [curve25519](https://en.wikipedia.org/wiki/Curve25519) in its operation. I think that this may be only applicable to the encryption used for messages in transit, though, and not to the encryption used for the on-disk message databases.

There are various tools for decoding the encypted backups produced by Signal, including [signalbackup-tools](https://github.com/bepaald/signalbackup-tools) and [signal_for_android_decryption](https://github.com/mossblaser/signal_for_android_decryption), but they are not designed to be used with the raw database files retrieved from the Android filesystem.

**Comment by DavidHenryThoreau** [comment]
There's also ; that may be needs to be adapted to Silence 
https://github.com/alexlance/signal-sms-mms-importer

**Comment by tmo1** [comment]
As I've said, I don't plan to try to figure out how to decrypt Silence's encrypted database files. If someone figures out how to do that, then I can try to help figure out how to get the resulting plaintext messages into a form readable by SMS I/E.

**Comment by DavidHenryThoreau** [comment]
And for MMS ? I've already exported SMS with commands above :smiley:

**Comment by tmo1** [comment]
> @tmo1 Silence can export to plaintext

I've already written a [Silence XML to SMS I/E JSON converter](https://github.com/tmo1/sms-ie/commit/a4d0fe1bd464756a8c3fe83ffbde51edf282fe1c); the problem, as @DavidHenryThoreau points out, is that this doesn't help for MMS messages, which Silence doesn't export at all, as @dngray himself has [noted above](https://github.com/tmo1/sms-ie/issues/121#issuecomment-1842184293), and are only available in Silence's internal database.

**Comment by tmo1** [comment]
> Why not enable export/import for SMS only for the time being?

I don't understand what you're asking for - transferring SMS messages from Silence is currently working fine via the converter I wrote, as I noted above. The workflow is:

1. Use Silence to export SMS messages in Silence XML format.
2. Use the SMS I/E Silence converter script to convert the XML file to a SMS I/E v2 compatible ZIP file.
3. Use SMS I/E to import the ZIP file.

**Comment by tmo1** [comment]
> I tried running python silence-convert.py SilencePlaintextBackup.xml but it spits this error:

[Read the documentation](https://github.com/tmo1/sms-ie/blob/master/tools/Tools.md#silence-convertpy).

**Comment by tarbib** [comment]
Hello all and espcially @tmo1, just wanted to say thank you
At first I started to do my own script and all but then I stumbled on this issue and my Silence page is now over.
Thanks a lot for your contributions!

**Comment by tmo1** [comment]
>  Thanks a lot for your contributions!

You're very welcome!

**Comment by ovz93br43v7** [comment]
Hi everyone, 

since the link to the fixer script ([https://git.silence.dev/Silence/Silence-Android/-/issues/317]) doesn't work for me and I'm not a programmer, I gave Gemini 2.5Pro the silence-convert.py script from @tmo1 tmo1 and asked it to implement a suitable cleanup function. 

**Please check before use!**


It worked for my Silence export with this version:

```python
#! /usr/bin/python3

# SMS Import / Export: a simple Android app for importing and exporting SMS and MMS messages,
# call logs, and contacts, from and to JSON / NDJSON files.
#
# Copyright (c) 2023 Thomas More
#
# This file is part of SMS Import / Export.
#
# SMS Import / Export is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# SMS Import / Export is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with SMS Import / Export.  If not, see <https://www.gnu.org/licenses/>

# This utility converts message in Silence (https://silence.im/) XML format to SMS I/E 'v2' format
# Usage: 'silence-convert.py <silence-xxx.xml>'
# This will read messages from <silence-xxx.xml> and write them to <silence-xxx.zip>.

import sys
import json
import xml.etree.ElementTree as ET
import zipfile
import os
import re # Module for regular expressions

# --- START OF CLEANUP FUNCTIONS ---

def is_invalid_xml_char_code(code):
    """
    Checks if a given decimal Unicode code point is invalid in XML 1.0.
    Invalid are: Control characters 0-8, 11-12, 14-31 and the surrogate range D800-DFFF (55296-57343).
    """
    # Control character ranges (except Tab=9, LF=10, CR=13)
    if 0 <= code <= 8: return True
    if 11 <= code <= 12: return True
    if 14 <= code <= 31: return True
    # Surrogate range
    if 55296 <= code <= 57343: return True
    # Otherwise, the code is valid
    return False

def check_and_replace_numeric_ref(match):
    """
    Callback function for re.sub. Checks a found numeric reference.
    Returns an empty string if it's invalid, otherwise the original.
    """
    try:
        if match.group(1): # Decimal match (group 1)
            code = int(match.group(1))
        elif match.group(2): # Hex match (group 2)
            code = int(match.group(2), 16)
        else:
            # Should not happen with the used regex, but better safe than sorry
             return match.group(0)

        if is_invalid_xml_char_code(code):
            # Invalid code -> replace with empty string
            # print(f"DEBUG: Removing invalid reference: {match.group(0)}") # Optional: Debugging
            return ""
        else:
            # Valid code -> keep original reference
            return match.group(0)
    except ValueError:
        # If something goes wrong with int() -> keep original
        return match.group(0)
    except Exception:
        # Other unexpected errors -> keep original
        return match.group(0)

def clean_xml_content(xml_string):
    """
    Cleans an XML string more comprehensively:
    1. Removes raw XML 1.0 invalid control characters.
    2. Finds all numeric character references (dec/hex) and removes
       those pointing to invalid code points (control characters or surrogates).
    """

    # 1. Regex to find and remove raw invalid control characters
    try:
        raw_invalid_chars_pattern = re.compile(r'[\x00-\x08\x0B\x0C\x0E-\x1F]')
        cleaned_string = raw_invalid_chars_pattern.sub('', xml_string)
        print(f"  (Step 1: Raw control characters removed)")
    except Exception as e:
        print(f"  (Error in Step 1 - Raw control characters: {e})")
        cleaned_string = xml_string # In case of error, continue with original string

    # 2. Regex to find *all* numeric character references (decimal OR hexadecimal)
    #    Group 1 captures the decimal value, group 2 the hex value
    try:
        numeric_ref_pattern = re.compile(r"&(?:#([0-9]+)|#x([0-9A-Fa-f]+));", re.IGNORECASE)

        # Use re.sub with the callback function to check each reference
        final_cleaned_string = numeric_ref_pattern.sub(check_and_replace_numeric_ref, cleaned_string)
        print(f"  (Step 2: Invalid numeric references (incl. surrogates) checked & potentially removed)")
    except Exception as e:
        print(f"  (Error in Step 2 - Checking numeric references: {e})")
        final_cleaned_string = cleaned_string # In case of error, continue with the string from step 1

    return final_cleaned_string

# --- END OF CLEANUP FUNCTIONS ---


# --- Main script logic ---

# Check if a filename was passed as an argument
if len(sys.argv) < 2:
    print("Error: Please provide the name of the input XML file.")
    print("Usage: python3 silence-convert.py <silence-xxx.xml>")
    sys.exit(1)

# Assign the first argument to the input_file variable
input_file = sys.argv[1]

# Read the content of the XML file
try:
    print(f"Reading XML file: {input_file}")
    # Try with UTF-8
    with open(input_file, 'r', encoding='utf-8') as f:
        xml_content = f.read()
except FileNotFoundError:
    print(f"Error: Input file not found: {input_file}")
    sys.exit(1)
except UnicodeDecodeError:
    try:
        print("Warning: Could not read file as UTF-8, trying latin-1...")
        with open(input_file, 'r', encoding='latin-1') as f:
            xml_content = f.read()
    except Exception as e:
        print(f"Error reading file {input_file} with fallback encoding: {e}")
        sys.exit(1)
except Exception as e:
    print(f"An unexpected error occurred while reading the file: {e}")
    sys.exit(1)

# Clean the XML content from invalid characters/references
print("Cleaning XML content (comprehensive attempt)...")
cleaned_xml_content = clean_xml_content(xml_content)

# Parse the cleaned XML string
print("Parsing cleaned XML content...")
try:
    # Use ET.fromstring as we have the content as a string
    root = ET.fromstring(cleaned_xml_content)
    smses = root # The root element is now 'root'
except ET.ParseError as e:
    # If parsing still fails, there might be another XML issue
    print(f"XML parsing failed even after comprehensive cleaning: {e}")
    print("The XML file might contain other errors or be severely corrupted.")
    # Debug info for the problematic line
    try:
        problem_line_num = e.position[0] # Get line number from the error
        lines = cleaned_xml_content.splitlines()
        if 0 < problem_line_num <= len(lines):
            print(f"--- Problematic line (No. {problem_line_num}) in *cleaned* content (excerpt): ---")
            # Show line before, the line itself, line after
            start = max(0, problem_line_num - 2)
            end = min(len(lines), problem_line_num + 1)
            for i in range(start, end):
                 print(f"{i+1}: {lines[i][:200]}") # Show max 200 characters per line
            print("--- End of excerpt ---")
        else:
             print("(Could not extract problematic line)")
    except Exception as debug_e:
        print(f"(Error extracting problematic line: {debug_e})")
    sys.exit(1)
except Exception as e:
    print(f"An unexpected error occurred while parsing the XML: {e}")
    sys.exit(1)

# Define the output filename (requires input_file)
output_file = input_file[:-3] + 'zip' if input_file.lower().endswith('.xml') else input_file + '.zip'

# Process messages and write ZIP
print(f"Processing messages and writing to ZIP file: {output_file}")
try:
    with zipfile.ZipFile(output_file, mode='w', compression=zipfile.ZIP_DEFLATED) as messages_zip:
        message_count = 0
        messages_ndjson = [] # Ensure the list is initialized here
        # Ensure 'smses' is iterable (the root element itself contains the 'sms'/'mms' tags)
        for sms in smses: # Iterate over the child elements of the root element
            # Convert the element's attributes into a dictionary
            message_data = dict(sms.attrib) # Use sms.attrib for XML attributes
            messages_ndjson.append(json.dumps(message_data) + '\n')
            message_count += 1

        if not messages_ndjson:
             print("Warning: No messages found or processed in the XML.")
        else:
            # Write the collected NDJSON lines to the file inside the ZIP
            messages_zip.writestr('messages.ndjson', ''.join(messages_ndjson))
            print(f"{message_count} messages successfully processed and written to {output_file}.")

except Exception as e:
    print(f"Error processing messages or writing the ZIP file: {e}")
    sys.exit(1)

print("Script finished.")
```
