### ISSUE TITLE
Crash when clicking any import/export

### ISSUE THREAD

**Issue by nabijaczleweli** [tmo1/sms-ie#178]
Lineage 16 (Android 9)

logcat sayeth:
```
04-21 23:37:44.487   495   507 I system_server: NativeAlloc concurrent copying GC freed 42554(2018KB) AllocSpace objects, 22(584KB) LOS objects, 42% free, 10MB/18MB, paused 366us total 250.793ms
04-21 23:37:44.770   495   605 W DropBoxManagerService: Dropping: system_app_strictmode (1941 > 0 bytes)
04-21 23:37:44.924   495   507 I system_server: NativeAlloc concurrent copying GC freed 6931(427KB) AllocSpace objects, 3(60KB) LOS objects, 42% free, 10MB/18MB, paused 2.960ms total 228.393ms
04-21 23:37:44.864   495   605 I chatty  : uid=1000(system) android.io identical 2 lines
04-21 23:37:44.908   495   605 W DropBoxManagerService: Dropping: system_app_strictmode (1941 > 0 bytes)
04-21 23:37:45.263   495   585 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10300000 cmp=com.github.tmo1.sms_ie/.MainActivity} from uid 10104
04-21 23:37:45.359  5278  5278 I Zygote  : seccomp disabled by setenforce 0
04-21 23:37:45.379   495   600 W ActivityManager: Slow operation: 70ms so far, now at startProcess: returned from zygote!
04-21 23:37:45.379   495   600 W ActivityManager: Slow operation: 70ms so far, now at startProcess: done updating battery stats
04-21 23:37:45.379   495   600 W ActivityManager: Slow operation: 70ms so far, now at startProcess: building log message
04-21 23:37:45.379   495   600 I ActivityManager: Start proc 5278:com.github.tmo1.sms_ie/u0a126 for activity com.github.tmo1.sms_ie/.MainActivity
04-21 23:37:45.379   495   600 W ActivityManager: Slow operation: 71ms so far, now at startProcess: starting to update pids map
04-21 23:37:45.379   495   600 W ActivityManager: Slow operation: 71ms so far, now at startProcess: done updating pids map
04-21 23:37:45.753  5278  5278 D OpenGLRenderer: Skia GL Pipeline
04-21 23:37:45.847   495   495 W Looper  : Slow dispatch took 116ms main h=com.android.server.notification.NotificationManagerService$WorkerHandler c=null m=3
04-21 23:37:45.927  5278  5304 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/21/15, 369a2ea, I96aee987eb
04-21 23:37:45.933  5278  5304 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
04-21 23:37:45.934  5278  5304 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
04-21 23:37:45.934  5278  5304 I OpenGLRenderer: Initialized EGL, version 1.4
04-21 23:37:45.934  5278  5304 D OpenGLRenderer: Swap behavior 1
04-21 23:37:45.945  5278  5304 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
04-21 23:37:45.963  5278  5304 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
04-21 23:37:45.965  5278  5304 D vndksupport: Loading /vendor/lib/hw/gralloc.msm8960.so from current namespace instead of sphal namespace.
04-21 23:37:46.101  5278  5304 D vndksupport: Loading /vendor/lib/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.
04-21 23:37:46.103  5278  5304 D vndksupport: Loading /vendor/lib/hw/gralloc.msm8960.so from current namespace instead of sphal namespace.
04-21 23:37:46.128  1842  1842 I HK/LatinKbdBaseView: closing org.pocketworkstation.pckeyboard.LatinKeyboardView{7d1cf25 V.ED..... ......ID 0,0-1080,624 #7f080004 app:id/LatinkeyboardBaseView}
04-21 23:37:46.134   495   597 I ActivityManager: Displayed com.github.tmo1.sms_ie/.MainActivity: +855ms
04-21 23:37:46.297   235   247 W SurfaceFlinger: Attempting to set client state on removed layer: Splash Screen com.github.tmo1.sms_ie#0
04-21 23:37:46.297   235   247 W SurfaceFlinger: Attempting to destroy on removed layer: Splash Screen com.github.tmo1.sms_ie#0
04-21 23:37:46.821   495  2550 I ActivityManager: START u0 {act=android.intent.action.CREATE_DOCUMENT cat=[android.intent.category.OPENABLE] typ=application/zip (has extras)} from uid 10126
04-21 23:37:46.829  5278  5278 D AndroidRuntime: Shutting down VM
04-21 23:37:46.831  5278  5278 E AndroidRuntime: FATAL EXCEPTION: main
04-21 23:37:46.831  5278  5278 E AndroidRuntime: Process: com.github.tmo1.sms_ie, PID: 5278
04-21 23:37:46.831  5278  5278 E AndroidRuntime: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.CREATE_DOCUMENT cat=[android.intent.category.OPENABLE] typ=application/zip (has extras) }
04-21 23:37:46.831  5278  5278 E AndroidRuntime: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2007)
04-21 23:37:46.831  5278  5278 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1673)
04-21 23:37:46.831  5278  5278 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4587)
04-21 23:37:46.831  5278  5278 E AndroidRuntime: 	at androidx.activity.n.startActivityForResult(SourceFile:2)
04-21 23:37:46.831  5278  5278 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4545)
04-21 23:37:46.831  5278  5278 E AndroidRuntime: 	at androidx.activity.n.startActivityForResult(SourceFile:1)
04-21 23:37:46.831  5278  5278 E AndroidRuntime: 	at c2.a0.onClick(SourceFile:405)
04-21 23:37:46.831  5278  5278 E AndroidRuntime: 	at android.view.View.performClick(View.java:6597)
04-21 23:37:46.831  5278  5278 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:6574)
04-21 23:37:46.831  5278  5278 E AndroidRuntime: 	at android.view.View.access$3100(View.java:778)
04-21 23:37:46.831  5278  5278 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:25906)
04-21 23:37:46.831  5278  5278 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
04-21 23:37:46.831  5278  5278 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-21 23:37:46.831  5278  5278 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
04-21 23:37:46.831  5278  5278 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
04-21 23:37:46.831  5278  5278 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-21 23:37:46.831  5278  5278 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
04-21 23:37:46.831  5278  5278 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
04-21 23:37:46.836   495  2550 W ActivityManager:   Force finishing activity com.github.tmo1.sms_ie/.MainActivity
04-21 23:37:46.868   495   599 I ActivityManager: Showing crash dialog for package com.github.tmo1.sms_ie u0
04-21 23:37:46.919   495  1651 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/21/15, 369a2ea, I96aee987eb
04-21 23:37:46.920   495  1651 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
04-21 23:37:46.920   495  1651 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
04-21 23:37:46.921   495  1651 I OpenGLRenderer: Initialized EGL, version 1.4
04-21 23:37:46.921   495  1651 D OpenGLRenderer: Swap behavior 1
04-21 23:37:46.927   495  1651 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
04-21 23:37:46.936   495  1651 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
04-21 23:37:46.937   495  1651 D vndksupport: Loading /vendor/lib/hw/gralloc.msm8960.so from current namespace instead of sphal namespace.
```
so
```
 android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.CREATE_DOCUMENT cat=[android.intent.category.OPENABLE] typ=application/zip (has extras) }
 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2007)
 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1673)
 	at android.app.Activity.startActivityForResult(Activity.java:4587)
 	at androidx.activity.n.startActivityForResult(SourceFile:2)
 	at android.app.Activity.startActivityForResult(Activity.java:4545)
 	at androidx.activity.n.startActivityForResult(SourceFile:1)
 	at c2.a0.onClick(SourceFile:405)
 	at android.view.View.performClick(View.java:6597)
 	at android.view.View.performClickInternal(View.java:6574)
 	at android.view.View.access$3100(View.java:778)
 	at android.view.View$PerformClick.run(View.java:25906)
 	at android.os.Handler.handleCallback(Handler.java:873)
 	at android.os.Handler.dispatchMessage(Handler.java:99)
 	at android.os.Looper.loop(Looper.java:193)
 	at android.app.ActivityThread.main(ActivityThread.java:6718)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
i think?

It looks like the action itself (API level 19) should be compatible with Android 9 (API 21), so I would expect the normal total commander "save as" file picker to show like it does at other times. idk

**Comment by nabijaczleweli** [comment]
Actually now that I click around other save-as actions it looks like this happens to all of them, so probably unrelated.
