### ISSUE TITLE
Unable to Export

### ISSUE THREAD

**Issue by strikekat** [tmo1/sms-ie#4]
Hi, I needed a no-nonsense app to export all my SMS messages to an open format as a backup before wiping this phone, and this looks like just what I need.
Unfortunately I'm not able to export at all. The app closes a few seconds after starting the export, and a 0-byte JSON file is written.
I'm on vanilla Android 11 on a Pixel 2XL.
I get this exception in logcat:
```
 5003 28074 E DatabaseUtils: Writing exception to parcel
08-23 11:38:51.585 25003 28074 E DatabaseUtils: java.lang.IllegalArgumentException: URI: content://com.android.contacts/phone_lookup/, calling user: com.github.tmo1.sms_ie, calling package:com.github.tmo1.sms_ie
08-23 11:38:51.585 25003 28074 E DatabaseUtils: 	at com.android.providers.contacts.LegacyApiSupport.query(LegacyApiSupport.java:1836)
08-23 11:38:51.585 25003 28074 E DatabaseUtils: 	at com.android.providers.contacts.ContactsProvider2.queryLocal(ContactsProvider2.java:6950)
08-23 11:38:51.585 25003 28074 E DatabaseUtils: 	at com.android.providers.contacts.ContactsProvider2.queryDirectoryIfNecessary(ContactsProvider2.java:5445)
08-23 11:38:51.585 25003 28074 E DatabaseUtils: 	at com.android.providers.contacts.ContactsProvider2.query(ContactsProvider2.java:5387)
08-23 11:38:51.585 25003 28074 E DatabaseUtils: 	at android.content.ContentProvider.query(ContentProvider.java:1475)
08-23 11:38:51.585 25003 28074 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:278)
08-23 11:38:51.585 25003 28074 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:106)
08-23 11:38:51.585 25003 28074 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1154)
08-23 11:38:51.585 25003 28074 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1123)
08-23 11:38:51.611 31581 31581 E AndroidRuntime: FATAL EXCEPTION: main
08-23 11:38:51.611 31581 31581 E AndroidRuntime: Process: com.github.tmo1.sms_ie, PID: 31581
08-23 11:38:51.611 31581 31581 E AndroidRuntime: java.lang.IllegalArgumentException: URI: content://com.android.contacts/phone_lookup/, calling user: com.github.tmo1.sms_ie, calling package:com.github.tmo1.sms_ie
08-23 11:38:51.611 31581 31581 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
08-23 11:38:51.611 31581 31581 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
08-23 11:38:51.611 31581 31581 E AndroidRuntime: 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:472)
08-23 11:38:51.611 31581 31581 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1183)
08-23 11:38:51.611 31581 31581 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1115)
08-23 11:38:51.611 31581 31581 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1071)
08-23 11:38:51.611 31581 31581 E AndroidRuntime: 	at com.github.tmo1.sms_ie.MainActivity$smsToJson$2.invokeSuspend(MainActivity.kt:186)
08-23 11:38:51.611 31581 31581 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
08-23 11:38:51.611 31581 31581 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
08-23 11:38:51.611 31581 31581 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
08-23 11:38:51.611 31581 31581 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
08-23 11:38:51.611 31581 31581 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
08-23 11:38:51.611 31581 31581 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

I thought that the query was perhaps failing because of a missing number or the like.
I went through my messages and deleted every conversation that wasn't a "normal" contact, such as ones from Verizon "900040001000", 5 digit senders, and Google, but I still get this same exception.
As far as I can tell, all the conversations left are normal stored contacts or phone numbers.

If there's any other debugging or information I can give, let me know (Although I do need to proceed with wiping and re-flashing this phone at some point).

**Comment by tmo1** [comment]
Thanks for reporting this. I tried the app on an emulated Pixel 2 XL running vanilla Android 11.0, and was not yet able to reproduce this. I haven't yet figured out what the problem might be - sorry. I'll look into it further when I get a chance, but if you need to wipe and flash your phone before this gets fixed, you can look into [Epistolaire](https://gitlab.com/hydrargyrum/epistolaire), which also claims to export to JSON (but it does not import).

**Comment by tmo1** [comment]
I wonder if this crash is triggered by SMS messages that lack associated sender phone numbers - the app tries to look up sender numbers in the the contacts database, and [this might throw an exception if the "number" is null or empty](https://stackoverflow.com/questions/6349566/illegalargumentexception-readexceptionfromparcel).

Can you check whether you have any SMS messages without sender numbers (perhaps ones that were send via email gateway, or some other unusual path)? If this is the problem, it will be easy to fix by inserting a check for null or empty numbers before querying the contacts database.

**Comment by strikekat** [comment]
I did try out Epistolaire, which unfortunately kept crashing due to an OOM error (I don't even use my phone that much, but I suppose it is almost 4 years of texts?).
I then tries SMS Gate and backing up to a local folder, which locked my phone up for a good 15-20 minutes, but did finally result in a folder of individual text files representing messages. Not ideal, but better than nothing.

I then analyzed these files, since the filenames include the recipient number, and I think I _maybe_ found the culprit:
`(taimen) 2020-02-04 17.09.54 ↑ --` (The dashes are supposed to be a phone number)

It looks like a message that I sent - to a contact that definitely normally has a phone number and is the majority of other messages in here. Absolutely no clue what happened there. Unfortunately I can't investigate further and try to find that message in the GUI or something.

Wasn't sure if `--` is literally part of the message's "recipient" or if it was empty, so looked at [SMS Gate's code ](https://gitlab.com/axet/android-sms-gate/-/blob/master/app/src/main/java/com/github/axet/smsgate/app/Storage.java#L157)and found this:
```java
if (TextUtils.isEmpty(address)) {
    sms.threadPhone = "--";
    sms.threadName = "--";
}
```
So probably safe to say it is empty or null.

**Comment by tmo1** [comment]
Hi,
Sorry for the delay in responding. If you still have the message list that causes sms-ie to crash and are interested in trying to fix the problem, I can provide a modified version of the program for you to test. Let me know if you're willing to try it.
