### ISSUE TITLE
Exporting contacts crash

### ISSUE THREAD

**Issue by thanasistrisp** [tmo1/sms-ie#50]
The first time worked, but not as expected (only one contact exported). I have multiple Google accounts with different contacts at each.
The second time I tried, the app crashed. Each time after I get this error:

```
FATAL EXCEPTION: main
Process: com.github.tmo1.sms_ie, PID: 15940
android.database.sqlite.SQLiteException: unknown error (code 0 SQLITE_OK[0]): Unable to convert BLOB to string
	at android.database.CursorWindow.nativeGetString(Native Method)
	at android.database.CursorWindow.getString(CursorWindow.java:480)
	at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:53)
	at android.database.CursorWrapper.getString(CursorWrapper.java:141)
	at com.github.tmo1.sms_ie.ImportExportContactsKt.contactsToJSON(ImportExportContacts.kt:135)
	at com.github.tmo1.sms_ie.ImportExportContactsKt.access$contactsToJSON(ImportExportContacts.kt:1)
	at com.github.tmo1.sms_ie.ImportExportContactsKt$contactsToJSON$1.invokeSuspend(Unknown Source:13)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by tmo1** [comment]
Thanks for reporting this. I have no idea why you only got one contact the first time, or why the app behaved differently between the first and subsequent runs, but I'm pretty sure I can guess what the error you've posted means: the app's code assumes that all the contacts data are strings (which is true in my case), but you apparently have some binary data in your contacts, such as images. I'll post a fixed version for you to try when I get a chance.

**Comment by tmo1** [comment]
I was able to reproduce the crash by adding a photo to a contact. The latest commit fixes the problem, at least in my testing. Would you please test [the fixed version](https://github.com/tmo1/sms-ie/files/9463236/sms_ie-handle-blob-data-in-contacts.zip) and report the results here?

**Comment by tmo1** [comment]
This is a new problem, so I'm closing this issue and opening a new one.
