### ISSUE TITLE
Out-of-memory crash when exporting MMS images

### ISSUE THREAD

**Issue by jbosboom** [tmo1/sms-ie#6]
When exporting with the "Include (encoded) binary MMS data" checkbox checked, after running for about 20 seconds, the application crashes ("has stopped") due to running out of memory, leaving an empty JSON file.  When the checkbox is unchecked, export completes without crashing and the JSON file contains valid data.

```
11-15 18:49:08.601 11485 12419 D ContactsProvider2ForLG: queryLocal match: 4000 return cursor
11-15 18:49:08.972 17914 17925 I zygote64: Background concurrent copying GC freed 4134(247KB) AllocSpace objects, 37(25MB) LOS objects, 23% free, 152MB/200MB, paused 7.609ms total 118.632ms
11-15 18:49:09.268 17914 17925 I zygote64: Background concurrent copying GC freed 1597(70KB) AllocSpace objects, 2(27MB) LOS objects, 19% free, 197MB/245MB, paused 31.778ms total 141.101ms
11-15 18:49:09.474 17914 18141 I zygote64: Starting a blocking GC Alloc
11-15 18:49:09.474 17914 18141 I zygote64: Starting a blocking GC Alloc
11-15 18:49:09.524 17914 18141 I zygote64: Alloc concurrent copying GC freed 637(45KB) AllocSpace objects, 1(36MB) LOS objects, 22% free, 161MB/209MB, paused 253us total 49.794ms
11-15 18:49:09.524 17914 18141 I zygote64: Starting a blocking GC Alloc
11-15 18:49:09.568 17914 18141 I zygote64: Alloc concurrent copying GC freed 6(16KB) AllocSpace objects, 0(0B) LOS objects, 22% free, 161MB/209MB, paused 296us total 43.477ms
11-15 18:49:09.568 17914 18141 I zygote64: Forcing collection of SoftReferences for 144MB allocation
11-15 18:49:09.568 17914 18141 I zygote64: Starting a blocking GC Alloc
11-15 18:49:09.652 17914 18141 I zygote64: Alloc concurrent copying GC freed 3611(127KB) AllocSpace objects, 0(0B) LOS objects, 22% free, 161MB/209MB, paused 288us total 83.743ms
11-15 18:49:09.652 17914 18141 W zygote64: Throwing OutOfMemoryError "Failed to allocate a 150994952 byte allocation with 50331648 free bytes and 94MB until OOM, max allowed footprint 219416160, growth limit 268435456"
11-15 18:49:09.652 17914 18141 I zygote64: Starting a blocking GC Alloc
11-15 18:49:09.652 17914 18141 I zygote64: Starting a blocking GC Alloc
11-15 18:49:09.693 17914 18141 I zygote64: Alloc concurrent copying GC freed 4(31KB) AllocSpace objects, 0(0B) LOS objects, 22% free, 161MB/209MB, paused 296us total 40.414ms
11-15 18:49:09.693 17914 18141 I zygote64: Starting a blocking GC Alloc
11-15 18:49:09.733 17914 18141 I zygote64: Alloc concurrent copying GC freed 3(16KB) AllocSpace objects, 0(0B) LOS objects, 22% free, 161MB/209MB, paused 286us total 40.092ms
11-15 18:49:09.733 17914 18141 I zygote64: Forcing collection of SoftReferences for 144MB allocation
11-15 18:49:09.733 17914 18141 I zygote64: Starting a blocking GC Alloc
11-15 18:49:09.817 17914 18141 I zygote64: Alloc concurrent copying GC freed 6(16KB) AllocSpace objects, 0(0B) LOS objects, 22% free, 161MB/209MB, paused 283us total 83.881ms
11-15 18:49:09.818 17914 18141 W zygote64: Throwing OutOfMemoryError "Failed to allocate a 150994952 byte allocation with 50331648 free bytes and 94MB until OOM, max allowed footprint 219416160, growth limit 268435456"
11-15 18:49:09.835 13042 13042 D MediaScannerReceiver: [MediaScanner] action: android.intent.action.MEDIA_SCANNER_SCAN_FILE
11-15 18:49:09.835 13042 13042 D MediaScannerReceiver: [MediaScanner] ACTION_MEDIA_SCANNER_SCAN_FILE
11-15 18:49:09.884 17914 17914 E AndroidRuntime: FATAL EXCEPTION: main
11-15 18:49:09.884 17914 17914 E AndroidRuntime: Process: com.github.tmo1.sms_ie, PID: 17914
11-15 18:49:09.884 17914 17914 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 150994952 byte allocation with 50331648 free bytes and 94MB until OOM, max allowed footprint 219416160, growth limit 268435456
11-15 18:49:09.884 17914 17914 E AndroidRuntime: 	at java.util.Arrays.copyOf(Arrays.java:3260)
11-15 18:49:09.884 17914 17914 E AndroidRuntime: 	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:125)
11-15 18:49:09.884 17914 17914 E AndroidRuntime: 	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:660)
11-15 18:49:09.884 17914 17914 E AndroidRuntime: 	at java.lang.StringBuilder.append(StringBuilder.java:203)
11-15 18:49:09.884 17914 17914 E AndroidRuntime: 	at org.json.JSONStringer.string(JSONStringer.java:344)
11-15 18:49:09.884 17914 17914 E AndroidRuntime: 	at org.json.JSONStringer.value(JSONStringer.java:252)
11-15 18:49:09.884 17914 17914 E AndroidRuntime: 	at org.json.JSONObject.writeTo(JSONObject.java:723)
11-15 18:49:09.884 17914 17914 E AndroidRuntime: 	at org.json.JSONStringer.value(JSONStringer.java:237)
11-15 18:49:09.884 17914 17914 E AndroidRuntime: 	at org.json.JSONArray.writeTo(JSONArray.java:613)
11-15 18:49:09.884 17914 17914 E AndroidRuntime: 	at org.json.JSONStringer.value(JSONStringer.java:233)
11-15 18:49:09.884 17914 17914 E AndroidRuntime: 	at org.json.JSONObject.writeTo(JSONObject.java:723)
11-15 18:49:09.884 17914 17914 E AndroidRuntime: 	at org.json.JSONStringer.value(JSONStringer.java:237)
11-15 18:49:09.884 17914 17914 E AndroidRuntime: 	at org.json.JSONArray.writeTo(JSONArray.java:613)
11-15 18:49:09.884 17914 17914 E AndroidRuntime: 	at org.json.JSONArray.toString(JSONArray.java:606)
11-15 18:49:09.884 17914 17914 E AndroidRuntime: 	at com.github.tmo1.sms_ie.MainActivity$smsToJson$2.invokeSuspend(MainActivity.kt:306)
11-15 18:49:09.884 17914 17914 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
11-15 18:49:09.884 17914 17914 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
11-15 18:49:09.884 17914 17914 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
11-15 18:49:09.884 17914 17914 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
11-15 18:49:09.884 17914 17914 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
11-15 18:49:09.884 17914 17914 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
11-15 18:49:09.889  1510  2716 W ActivityManager:   Force finishing activity com.github.tmo1.sms_ie/.MainActivity
```

LG G6, Android 8.

I'm not an Android developer and haven't looked at Kotlin before, but it seems you're accumulating the entire JSON object in memory before writing anything to a file.  If streaming writes are not possible, maybe you should write MMS binary data to separate files in small batches and leave it up to other software to join them based on the message ID.

**Comment by tmo1** [comment]
Thanks for reporting this!

> I'm not an Android developer and haven't looked at Kotlin before, but it seems you're accumulating the entire JSON object in memory before writing anything to a file.

Yes, that's the current (admittedly naive) implementation. It works fine on my test collection of messages, which includes ~800 MMS messages with only a handful of GIFs and so on, where the resulting file size is only ~20MB, but I can easily imagine that it would run into trouble with message collections with a lot more binary data. (In your report, it looks like the failure is occurring on an attempt to allocate a 150MB block of memory.)

> If streaming writes are not possible, maybe you should write MMS binary data to separate files in small batches and leave it up to other software to join them based on the message ID.

The truth is that I agonized for a while over the architectural decision of whether to include the binary data in the main JSON file (as [Synctech's SMS Backup and Restore](https://synctech.com.au/sms-backup-restore/fields-in-xml-backup-files/) does), or as separate files (as you suggest, and as [signal-backup-decode](https://github.com/pajowu/signal-backup-decode) does). I went with the former, largely due the coding being simpler and cleaner, but it certainly does have its downsides.

Insofar as we keep the current architecture, the most straightforward fix for the problem is (as you allude) would seem to be to switch from a JSON object model to [a streaming one](https://developer.android.com/reference/kotlin/android/util/JsonWriter). This should be pretty straightforward - I'll look into implementing it when I get a chance.

**Comment by tmo1** [comment]
Okay, I've switched to a JSON stream for export, which should fix your error. I'm going to leave this issue open, though, until I switch the import code as well.

**Comment by jbosboom** [comment]
I just successfully exported my MMS messages into an 86 MB file.  Thanks for your work and sorry for the delay in testing.

**Comment by tmo1** [comment]
Great! I'm glad it's working now - thanks for the confirmation.
