### ISSUE TITLE
Crash when export MMS.

### ISSUE THREAD

**Issue by chan1108** [tmo1/sms-ie#87]
12-28 22:29:05.550 21929 21929 E AndroidRuntime: Process: com.github.tmo1.sms_ie, PID: 21929
12-28 22:29:05.550 21929 21929 E AndroidRuntime: android.database.sqlite.SQLiteException: unknown error (code 0 SQLITE_OK): Unable to convert BLOB to string
12-28 22:29:05.550 21929 21929 E AndroidRuntime:        at android.database.CursorWindow.nativeGetString(Native Method)
12-28 22:29:05.550 21929 21929 E AndroidRuntime:        at android.database.CursorWindow.getString(CursorWindow.java:465)
12-28 22:29:05.550 21929 21929 E AndroidRuntime:        at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:54)
12-28 22:29:05.550 21929 21929 E AndroidRuntime:        at android.database.CursorWrapper.getString(CursorWrapper.java:203)
12-28 22:29:05.550 21929 21929 E AndroidRuntime:        at com.github.tmo1.sms_ie.ImportExportMessagesKt.mmsToJSON(ImportExportMessages.kt:205)
12-28 22:29:05.550 21929 21929 E AndroidRuntime:        at com.github.tmo1.sms_ie.ImportExportMessagesKt.access$mmsToJSON(ImportExportMessages.kt:1)
12-28 22:29:05.550 21929 21929 E AndroidRuntime:        at com.github.tmo1.sms_ie.ImportExportMessagesKt$mmsToJSON$1.invokeSuspend(Unknown Source:17)
12-28 22:29:05.550 21929 21929 E AndroidRuntime:        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
12-28 22:29:05.550 21929 21929 E AndroidRuntime:        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
12-28 22:29:05.550 21929 21929 E AndroidRuntime:        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
12-28 22:29:05.550 21929 21929 E AndroidRuntime:        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
12-28 22:29:05.550 21929 21929 E AndroidRuntime:        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
12-28 22:29:05.550 21929 21929 E AndroidRuntime:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
12-28 22:29:05.550 21929 21929 E AndroidRuntime:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
12-28 22:29:05.550 21929 21929 E AndroidRuntime:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
12-28 22:29:05.550 21929 21929 E AndroidRuntime:        Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@a5a2900, Dispatchers.Main]

veision:1.5.3

**Comment by tmo1** [comment]
Thanks for reporting this, but I don't understand it at all: there should not **be** any BLOBs in the database table we're querying there, [according to the official documentation](https://developer.android.com/reference/android/provider/Telephony.Mms.Part). When I get a chance, I'll post a version of the app that will log exactly where it's hitting the error, so I can try to figure out what's going on.

**Comment by tmo1** [comment]
Okay - please test [this build](https://github.com/tmo1/sms-ie/files/10435950/sms_ie-catch-unexpected-blobs.zip), which should catch and log the details of the problem. The app should recover and not crash, but please search the logcat for any `SQLiteException`s and post them here. The logcat should contain the names and values of the problematic fields - redact the values as appropriate.

**Comment by tmo1** [comment]
Closing to submitter unresponsiveness; feel free to reopen as appropriate.

**Comment by tmo1** [comment]
Thanks for reporting this. I'll try to provide a version of the app that will catch and log the problem, so we can try to figure out what's causing the problem and how to work around it.

**Comment by Bliss161** [comment]
Thank you and yes of course!

Using this build if it matters https://github.com/tmo1/sms-ie/actions/runs/20039370146

```
12-29 18:19:02.842 10663 11529 E SMSIE   : EXPORT_MESSAGES_MANUAL failed
12-29 18:19:02.842 10663 11529 E SMSIE   : android.database.sqlite.SQLiteException: unknown error (code 0 SQLITE_OK): Unable to convert BLOB to string
12-29 18:19:02.842 10663 11529 E SMSIE   : 	at android.database.CursorWindow.nativeGetString(Native Method)
12-29 18:19:02.842 10663 11529 E SMSIE   : 	at android.database.CursorWindow.getString(CursorWindow.java:469)
12-29 18:19:02.842 10663 11529 E SMSIE   : 	at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:53)
12-29 18:19:02.842 10663 11529 E SMSIE   : 	at android.database.CursorWrapper.getString(CursorWrapper.java:141)
12-29 18:19:02.842 10663 11529 E SMSIE   : 	at com.github.tmo1.sms_ie.ImportExportMessagesKt.mmsToJSON(ImportExportMessages.kt:193)
12-29 18:19:02.842 10663 11529 E SMSIE   : 	at com.github.tmo1.sms_ie.ImportExportMessagesKt.access$mmsToJSON(ImportExportMessages.kt:1)
12-29 18:19:02.842 10663 11529 E SMSIE   : 	at com.github.tmo1.sms_ie.ImportExportMessagesKt$mmsToJSON$1.invokeSuspend(Unknown Source:17)
12-29 18:19:02.842 10663 11529 E SMSIE   : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
12-29 18:19:02.842 10663 11529 E SMSIE   : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
12-29 18:19:02.842 10663 11529 E SMSIE   : 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:124)
12-29 18:19:02.842 10663 11529 E SMSIE   : 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
12-29 18:19:02.842 10663 11529 E SMSIE   : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:586)
12-29 18:19:02.842 10663 11529 E SMSIE   : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:820)
12-29 18:19:02.842 10663 11529 E SMSIE   : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:717)
12-29 18:19:02.842 10663 11529 E SMSIE   : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:704)
12-29 18:19:02.843 10663 11529 I SMSIE   : EXPORT_MESSAGES_MANUAL result: Failure {mOutputData=Data {title : Messages export error, message : unknown error (code 0 SQLITE_OK): Unable to convert BLOB to string
```

**Comment by tmo1** [comment]
> Using this build if it matters

Excellent - thanks.

The problem seems to be that the app assumes that all values in the MMS table are strings and accordingly tries to access them with `getString()`, but in actuality Android occasionally (rarely?) stores values as BLOBs, and these values must be accessed with `getBlob()` ([as we already do when exporting contacts](https://github.com/tmo1/sms-ie/blob/efa7ecb9c7f9e616277f12273c4a64fefc907c04/app/src/main/java/com/github/tmo1/sms_ie/ImportExportContacts.kt#L133)).

I'm going to upload a version of the app that will try to catch and log the MMS messages that contain BLOBs, and once we have a better picture of the context in which these BLOBs appear, I'll try to fix the app to handle them properly.

**Comment by maverick74** [comment]
Great! I'm very interested in this fix 🙂

**Comment by tmo1** [comment]
Here's [a version of the app](https://github.com/user-attachments/files/24388107/sms_ie-blob-handling.zip) that writes all non-BLOB data as before, and writes BLOB data after base64 encoding it and modifying the tag name into the form `<original_tag>__base64__`.

I aske anyone who has experienced this problem to please run this version and inspect its output. Try to verify that the output seems correct, and search for tag names with the `__base64__` suffix and report how many there are, what the tag names are, and what sort of data they seem to contain (the data can be base64 decoded using local tools, or an online tool such as [CyberChef](https://gchq.github.io/CyberChef/)).

**Comment by Bliss161** [comment]
Thanks for that version, I was able to export without any issues.

I have 40 instances of one tag "preview_data__base64__" and they are JPEG File Interchange Format (JFIF) and Exchangeable Image File Format (EXIF) about 20kb each.

This is coming from a MIUI 12.1.4 (Android 11) device, though those messages might have been restored from something even older.

**Comment by tmo1** [comment]
> Thanks for that version, I was able to export without any issues.

Perfect - thanks!

> I have 40 instances of one tag "preview_data__base64__" and they are JPEG File Interchange Format (JFIF) and Exchangeable Image File Format (EXIF) about 20kb each.

So some version of Android (MIUI?) is apparently storing previews of MMS images in the MMS database itself (as opposed to the actual images, which Android stores separately, as files in the device filesystem).

This `preview_data` column is not mentioned in the official Android documentation - actually, I can't find any mention of it whatsoever online. As Google's "AI Overview" puts it:

> The column named preview_data is not a standard, documented column in the public android.provider.Telephony.Mms content provider API. The standard columns are defined within the Telephony contract classes. 

Google AI continues:

> The preview_data column likely exists in some custom or vendor-specific implementations of the Telephony Provider. Such columns are often used internally by a specific manufacturer's messaging app to cache a visual preview or thumbnail of the MMS content (like an image) for faster display in the conversation list, without having to parse the entire MMS structure.

I can't find an actual source for this, but it's likely accurate.

I plan to add the behavior implemented in the above build to the app, with the addition of a settings toggle to just skip BLOB data upon export, in order to keep the file size down and to avoid cluttering the more-or-less readable JSON with relatively  large chunks of encoded binary data.

The app as currently designed should just ignore the exported BLOB data upon import, since it only imports tag-value pairs whose tags are present in the target device's MMS database, and the `__base64__` suffixes should ensure that they won't be. At least at this point, I'm not going to implement the import of non-standard BLOB data, since it isn't possible at all on standard devices that don't have the non-standard columns, and I'm not sure how much value importing such data would add even on devices that do have the appropriate columns.

> This is coming from a MIUI 12.1.4 (Android 11) device, though those messages might have been restored from something even older.

You can examine the dates of the messages (as found in their `date` fields) and check what device you were using at the time.

**Comment by tmo1** [comment]
> I didn't check anything else but exporting and importing occurred without any errors!

Great, thanks!

> Haven't got the time yet to take a closer look neither at the messages themselves neither to anything else you asked (sorry!)

I'm particularly interested in knowing whether all these BLOBS are in the `preview_data` column, or whether there are other BLOB-containing columns, so please report back when you get a chance.

**Comment by tmo1** [comment]
> OK, i've got 133 "preview_data__base64__" tags.

Thanks!

Version 2.8.0, which includes the fix for this issue, has just been released.
